//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DONVI
    {
        public string IDDONVI { get; set; }
        public string TENDONVI { get; set; }
        public string MACTY { get; set; }
        public Nullable<int> PHONE { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
    }
}
